// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCoiCOdAyXE2OJfd63lSYdjjalpdld10X8',
    appId: '1:779848765742:web:051c231ff915378d8f6abf',
    messagingSenderId: '779848765742',
    projectId: 'final-project-85174',
    authDomain: 'final-project-85174.firebaseapp.com',
    storageBucket: 'final-project-85174.firebasestorage.app',
    measurementId: 'G-8TK0FZDEYE',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDS05p7U-YuJEEiWRzJ_SxxxbQDrau8vxc',
    appId: '1:779848765742:android:a6ed98ed42cb319f8f6abf',
    messagingSenderId: '779848765742',
    projectId: 'final-project-85174',
    storageBucket: 'final-project-85174.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBEVkBHVSwIxF0yFbm-j0FaXcaXfjdraTE',
    appId: '1:779848765742:ios:f2ac52022d9533dc8f6abf',
    messagingSenderId: '779848765742',
    projectId: 'final-project-85174',
    storageBucket: 'final-project-85174.firebasestorage.app',
    iosBundleId: 'com.example.finalProject',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBEVkBHVSwIxF0yFbm-j0FaXcaXfjdraTE',
    appId: '1:779848765742:ios:f2ac52022d9533dc8f6abf',
    messagingSenderId: '779848765742',
    projectId: 'final-project-85174',
    storageBucket: 'final-project-85174.firebasestorage.app',
    iosBundleId: 'com.example.finalProject',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCoiCOdAyXE2OJfd63lSYdjjalpdld10X8',
    appId: '1:779848765742:web:d353ec80ff5f0e678f6abf',
    messagingSenderId: '779848765742',
    projectId: 'final-project-85174',
    authDomain: 'final-project-85174.firebaseapp.com',
    storageBucket: 'final-project-85174.firebasestorage.app',
    measurementId: 'G-GLE4ESQBP2',
  );
}
